### ISSUE TITLE
Deploy triggers internal error

### ISSUE THREAD

**Issue by cbou** [scaleway/serverless-scaleway-functions#30]
I get an error when I try to deploy a package.

The new function is correctly deployed and runs without an issue.

The command line returns an error and the Scaleaway website shows an error as well...

<img width="326" alt="Screenshot 2020-10-30 at 20 29 37" src="https://user-images.githubusercontent.com/611389/97749024-a7854600-1aee-11eb-83a6-08229cce7b49.png">

```
$ sls deploy --scw-token=`cat .scw-token` --scw-organization=`cat .scw-organization-id`

Serverless: Using credentials from command line parameters
Serverless: Using credentials from command line parameters
Serverless: Using credentials from command line parameters
Serverless: Using credentials from command line parameters
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Updating function sendmail...
Serverless: Uploading source code...
Serverless: Deploying Functions...
Serverless: Waiting for function deployments, this may take multiple minutes...
 
  Error --------------------------------------------------
 
  Error: internal error
      at listFunctions.then (/Users/charles/serverless/serverless-scaleway-functions/shared/api/functions.js:45:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.1
     Framework Version:         1.65.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sendmail@1.0.0 deploy: `sls deploy --scw-token=`cat .scw-token` --scw-organization=`cat .scw-organization-id``
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sendmail@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/charles/.npm/_logs/2020-10-30T18_49_52_601Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/charles/.nvm/versions/node/v10.15.1/bin/node',
1 verbose cli   '/Users/charles/.nvm/versions/node/v10.15.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@6.14.8
3 info using node@v10.15.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle sendmail@1.0.0~predeploy: sendmail@1.0.0
6 info lifecycle sendmail@1.0.0~deploy: sendmail@1.0.0
7 verbose lifecycle sendmail@1.0.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle sendmail@1.0.0~deploy: PATH: /Users/charles/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/charles/Pidoco/serverless/node_modules/.bin:/Users/charles/.rvm/gems/ruby-2.5.2/bin:/Users/charles/.rvm/gems/ruby-2.5.2@global/bin:/Users/charles/.rvm/rubies/ruby-2.5.2/bin:/Users/charles/.yarn/bin:/Users/charles/.config/yarn/global/node_modules/.bin:/Users/charles/.nvm/versions/node/v10.15.1/bin:/Users/charles/.composer/vendor/bin:/Users/charles/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/charles/.rvm/bin:/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/bin
9 verbose lifecycle sendmail@1.0.0~deploy: CWD: /Users/charles/serverless
10 silly lifecycle sendmail@1.0.0~deploy: Args: [ '-c',
10 silly lifecycle   'sls deploy --scw-token=`cat .scw-token` --scw-organization=`cat .scw-organization-id`' ]
11 silly lifecycle sendmail@1.0.0~deploy: Returned: code: 1  signal: null
12 info lifecycle sendmail@1.0.0~deploy: Failed to exec deploy script
13 verbose stack Error: sendmail@1.0.0 deploy: `sls deploy --scw-token=`cat .scw-token` --scw-organization=`cat .scw-organization-id``
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/charles/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/charles/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid sendmail@1.0.0
15 verbose cwd /Users/charles/Pidoco/serverless
16 verbose Darwin 19.6.0
17 verbose argv "/Users/charles/.nvm/versions/node/v10.15.1/bin/node" "/Users/charles/.nvm/versions/node/v10.15.1/bin/npm" "run" "deploy"
18 verbose node v10.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error sendmail@1.0.0 deploy: `sls deploy --scw-token=`cat .scw-token` --scw-organization=`cat .scw-organization-id``
22 error Exit status 1
23 error Failed at the sendmail@1.0.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cbou** [comment]
Same issue with a recent version of serverless
```
Framework Core: 2.9.0
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.3.0
```
