### ISSUE TITLE
Add support for "serverless info"

### ISSUE THREAD

**Issue by n-Arno** [scaleway/serverless-scaleway-functions#71]
Currently, using serverless info yield an error with the scaleway plugin:

```
$ serverless info
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Using credentials from system environment
Environment: darwin, node 17.8.0, framework 3.16.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at resolveArgsSchema (/usr/local/lib/node_modules/serverless/lib/cli/resolve-input.js:13:45)
    at /usr/local/lib/node_modules/serverless/lib/cli/resolve-input.js:41:5
    at memoized (/usr/local/lib/node_modules/serverless/node_modules/memoizee/lib/configure-map.js:80:41)
    at /usr/local/lib/node_modules/serverless/scripts/serverless.js:610:15
    at /usr/local/lib/node_modules/serverless/scripts/serverless.js:745:9
```

**Comment by n-Arno** [comment]
This commit add a thin layer of info compatible with serverless-compose: https://github.com/n-Arno/serverless-scaleway-functions/commit/0648b117812d5ce714ec86ba5c2999a98430940b
